/**
 *
 * @author David Beltran
 * File: CarShowMainMenu.java
 * This file contains the CarShowMainMenu class which is responsible for
 * displaying and running the car show application's main menu GUI
 */
package edu.du.beltrandavid.view;

import edu.du.beltrandavid.controllor.CarShowMainMenuController;
import edu.du.beltrandavid.model.business.manager.carshowmanager.CarShowManager;
import edu.du.beltrandavid.model.business.manager.carshowownermanager.CarShowOwnerManager;
import edu.du.beltrandavid.model.business.manager.ownermanager.OwnerManager;
import edu.du.beltrandavid.model.business.manager.persistmanager.PersistManager;
import edu.du.beltrandavid.model.business.manager.vehiclemanager.VehicleManager;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CarShowMainMenu extends javax.swing.JFrame {
  
  private static OwnerManager ownerManager = new OwnerManager();
  private static VehicleManager vehicleManager = new VehicleManager();
  private static CarShowManager carShowManager = new CarShowManager();
  private static CarShowOwnerManager carShowOwnerManager = new CarShowOwnerManager();
  private static PersistManager persistManager = new PersistManager();
  
  private final Container container = getContentPane();

  /**
   * Creates new form CarShowMainMenu
   * @throws java.lang.Exception
   */
  public CarShowMainMenu() throws Exception {
    
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension windowSize = new Dimension((screenSize.width / 2) - 120, 
        (screenSize.height / 2) + 90);
    setPreferredSize(windowSize);
    setLocation(((screenSize.width - windowSize.width) / 2), 
        ((screenSize.height - windowSize.height) / 2));
    
    setTitle("Car Show Main Menu");
    
    initComponents();
    setServicePropertiesFile("serviceproperties.txt");
    persistManager.setPersistProperties("persistenceproperties.txt");
    persistManager.loadPersistData(ownerManager, vehicleManager, carShowManager, 
        carShowOwnerManager);
    CarShowMainMenuController carShowMainMenuController = new CarShowMainMenuController(this);
    
    ownerMainMenuButton.setEnabled(false);
    vehicleMainMenuButton.setEnabled(false);
    carShowMainMenuButton.setEnabled(false);
    carShowOwnerMainMenuButton.setEnabled(false);
    printReportMainMenuButton.setEnabled(false);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    clickCollectionHeaderLabel = new javax.swing.JLabel();
    carShowCsoPanel = new javax.swing.JPanel();
    carShowMainMenuButton = new javax.swing.JButton();
    carShowOwnerMainMenuButton = new javax.swing.JButton();
    ownerVehiclePanel = new javax.swing.JPanel();
    ownerMainMenuButton = new javax.swing.JButton();
    vehicleMainMenuButton = new javax.swing.JButton();
    printReportPanel = new javax.swing.JPanel();
    printReportMainMenuButton = new javax.swing.JButton();
    loginPanel = new javax.swing.JPanel();
    loginHeaderLabel = new javax.swing.JLabel();
    userIdLabel = new javax.swing.JLabel();
    passwordLabel = new javax.swing.JLabel();
    userIdTextField = new javax.swing.JTextField();
    passwordTextField = new javax.swing.JPasswordField();
    submitMainMenuButton = new javax.swing.JButton();
    carShowMainMenuBar = new javax.swing.JMenuBar();
    fileMainMenuItem = new javax.swing.JMenu();
    exitMenuItem = new javax.swing.JMenuItem();
    editMainMenuItem = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    clickCollectionHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    clickCollectionHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    clickCollectionHeaderLabel.setText("Click On a Collection");
    clickCollectionHeaderLabel.setToolTipText("");

    carShowMainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    carShowMainMenuButton.setText("CAR SHOW");
    carShowMainMenuButton.setToolTipText("");
    carShowMainMenuButton.setNextFocusableComponent(carShowOwnerMainMenuButton);

    carShowOwnerMainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    carShowOwnerMainMenuButton.setText("CAR SHOW OWNER");
    carShowOwnerMainMenuButton.setToolTipText("");
    carShowOwnerMainMenuButton.setNextFocusableComponent(fileMainMenuItem);

    javax.swing.GroupLayout carShowCsoPanelLayout = new javax.swing.GroupLayout(carShowCsoPanel);
    carShowCsoPanel.setLayout(carShowCsoPanelLayout);
    carShowCsoPanelLayout.setHorizontalGroup(
      carShowCsoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(carShowCsoPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(carShowCsoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(carShowOwnerMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(carShowMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    carShowCsoPanelLayout.setVerticalGroup(
      carShowCsoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(carShowCsoPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(carShowMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(carShowOwnerMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    ownerMainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    ownerMainMenuButton.setText("OWNER");
    ownerMainMenuButton.setToolTipText("Click to Manage Owners");
    ownerMainMenuButton.setFocusCycleRoot(true);
    ownerMainMenuButton.setNextFocusableComponent(vehicleMainMenuButton);

    vehicleMainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    vehicleMainMenuButton.setText("VEHICLE");
    vehicleMainMenuButton.setNextFocusableComponent(carShowMainMenuButton);

    javax.swing.GroupLayout ownerVehiclePanelLayout = new javax.swing.GroupLayout(ownerVehiclePanel);
    ownerVehiclePanel.setLayout(ownerVehiclePanelLayout);
    ownerVehiclePanelLayout.setHorizontalGroup(
      ownerVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ownerVehiclePanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(ownerVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(ownerMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ownerVehiclePanelLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(vehicleMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    ownerVehiclePanelLayout.setVerticalGroup(
      ownerVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ownerVehiclePanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(ownerMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(vehicleMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    printReportMainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    printReportMainMenuButton.setText("PRINT REPORT");
    printReportMainMenuButton.setToolTipText("");

    javax.swing.GroupLayout printReportPanelLayout = new javax.swing.GroupLayout(printReportPanel);
    printReportPanel.setLayout(printReportPanelLayout);
    printReportPanelLayout.setHorizontalGroup(
      printReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(printReportPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(printReportMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    printReportPanelLayout.setVerticalGroup(
      printReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(printReportPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(printReportMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    loginHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    loginHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    loginHeaderLabel.setText("Login to use");
    loginHeaderLabel.setToolTipText("");

    userIdLabel.setText("UserID");
    userIdLabel.setToolTipText("");

    passwordLabel.setText("Password");
    passwordLabel.setToolTipText("");

    userIdTextField.setToolTipText("Enter your user ID");

    passwordTextField.setToolTipText("Enter your password");

    submitMainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    submitMainMenuButton.setText("Submit");

    javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
    loginPanel.setLayout(loginPanelLayout);
    loginPanelLayout.setHorizontalGroup(
      loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(loginPanelLayout.createSequentialGroup()
        .addGap(210, 210, 210)
        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(submitMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(loginHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(loginPanelLayout.createSequentialGroup()
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(userIdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
              .addComponent(userIdTextField))))
        .addContainerGap(183, Short.MAX_VALUE))
    );
    loginPanelLayout.setVerticalGroup(
      loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(loginPanelLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(loginHeaderLabel)
        .addGap(18, 18, 18)
        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(userIdLabel)
          .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(passwordLabel)
          .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(submitMainMenuButton))
    );

    fileMainMenuItem.setText("File");

    exitMenuItem.setText("Exit");
    exitMenuItem.setToolTipText("Exit the System");
    fileMainMenuItem.add(exitMenuItem);

    carShowMainMenuBar.add(fileMainMenuItem);

    editMainMenuItem.setText("Edit");
    carShowMainMenuBar.add(editMainMenuItem);

    setJMenuBar(carShowMainMenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(186, 186, 186)
            .addComponent(printReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(251, 251, 251)
            .addComponent(clickCollectionHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(ownerVehiclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carShowCsoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addContainerGap(36, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(34, 34, 34)
        .addComponent(clickCollectionHeaderLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(carShowCsoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ownerVehiclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(printReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * 
   * @param file 
   * sets the service properties file to all Manager objects
   */
  public static void setServicePropertiesFile(String file) {
    ownerManager.setServiceProperties(file);
    vehicleManager.setServiceProperties(file);
    carShowManager.setServiceProperties(file);
    carShowOwnerManager.setServiceProperties(file);
  }
  
  /**
   * @throws Exception
   */
  public static void runPortfolioProject() throws Exception {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CarShowMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CarShowMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CarShowMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CarShowMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        try {
          new CarShowMainMenu().setVisible(true);
        } catch (Exception ex) {
          Logger.getLogger(CarShowMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel carShowCsoPanel;
  private javax.swing.JMenuBar carShowMainMenuBar;
  private javax.swing.JButton carShowMainMenuButton;
  private javax.swing.JButton carShowOwnerMainMenuButton;
  private javax.swing.JLabel clickCollectionHeaderLabel;
  private javax.swing.JMenu editMainMenuItem;
  private javax.swing.JMenuItem exitMenuItem;
  private javax.swing.JMenu fileMainMenuItem;
  private javax.swing.JLabel loginHeaderLabel;
  private javax.swing.JPanel loginPanel;
  private javax.swing.JButton ownerMainMenuButton;
  private javax.swing.JPanel ownerVehiclePanel;
  private javax.swing.JLabel passwordLabel;
  private javax.swing.JPasswordField passwordTextField;
  private javax.swing.JButton printReportMainMenuButton;
  private javax.swing.JPanel printReportPanel;
  private javax.swing.JButton submitMainMenuButton;
  private javax.swing.JLabel userIdLabel;
  private javax.swing.JTextField userIdTextField;
  private javax.swing.JButton vehicleMainMenuButton;
  // End of variables declaration//GEN-END:variables

  /**
   *
   * @return
   */
  public javax.swing.JMenuBar getCarShowMainMenuBar() {
    return carShowMainMenuBar;
  }

  /**
   *
   * @return
   */
  public javax.swing.JButton getCarShowMainMenuButton() {
    return carShowMainMenuButton;
  }

  /**
   *
   * @return
   */
  public javax.swing.JButton getCarShowOwnerMainMenuButton() {
    return carShowOwnerMainMenuButton;
  }

  /**
   *
   * @return
   */
  public javax.swing.JMenu getEditMainMenuItem() {
    return editMainMenuItem;
  }

  /**
   * 
   * @return 
   */
  public javax.swing.JButton getSubmitMainMenuButton() {
    return submitMainMenuButton;
  }
  
  /**
   *
   * @return
   */
  public javax.swing.JLabel getLoginHeaderLabel() {
    return loginHeaderLabel;
  }
  
  /**
   *
   * @return
   */
  public javax.swing.JLabel getUserIdLabel() {
    return userIdLabel;
  }
  
  /**
   *
   * @return
   */
  public javax.swing.JLabel getPasswordLabel() {
    return passwordLabel;
  }
  
  /**
   *
   * @return
   */
  public javax.swing.JTextField getUserIdTextField() {
    return userIdTextField;
  }
  
  /**
   *
   * @return
   */
  public javax.swing.JPasswordField getPasswordTextField() {
    return passwordTextField;
  }
  
  /**
   *
   * @return
   */
  public javax.swing.JMenuItem getExitMenuItem() {
    return exitMenuItem;
  }

  /**
   *
   * @return
   */
  public javax.swing.JMenu getFileMainMenuItem() {
    return fileMainMenuItem;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getMainMenuHeaderLabel() {
    return clickCollectionHeaderLabel;
  }

  /**
   *
   * @return
   */
  public javax.swing.JButton getOwnerMainMenuButton() {
    return ownerMainMenuButton;
  }

  /**
   *
   * @return
   */
  public javax.swing.JButton getVehicleMainMenuButton() {
    return vehicleMainMenuButton;
  }

  /**
   *
   * @return
   */
  public javax.swing.JButton getPrintReportMainMenuButton() {
    return printReportMainMenuButton;
  }
  
  /**
   *
   * @return
   */
  public static OwnerManager getOwnerManager() {
    return ownerManager;
  }

  /**
   *
   * @return
   */
  public static VehicleManager getVehicleManager() {
    return vehicleManager;
  }

  /**
   *
   * @return
   */
  public static CarShowManager getCarShowManager() {
    return carShowManager;
  }

  /**
   *
   * @return
   */
  public static CarShowOwnerManager getCarShowOwnerManager() {
    return carShowOwnerManager;
  }

  /**
   *
   * @return
   */
  public static PersistManager getPersistManager() {
    return persistManager;
  }

  /**
   *
   * @return
   */
  public Container getContainer() {
    return container;
  }
}
