/**
 *
 * @author David Beltran
 * File: CarShowUI.java
 * This file contains the CarShowUI class which is responsible for
 * displaying and running the car show application's CarShow GUI
 */
package edu.du.beltrandavid.view;

import edu.du.beltrandavid.controllor.carshowcontroller.CarShowUIController;
import edu.du.beltrandavid.model.business.manager.carshowmanager.CarShowManager;
import edu.du.beltrandavid.model.business.manager.carshowownermanager.CarShowOwnerManager;
import edu.du.beltrandavid.model.business.manager.ownermanager.OwnerManager;
import edu.du.beltrandavid.model.business.manager.vehiclemanager.VehicleManager;
import edu.du.beltrandavid.model.domain.CarShow;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Iterator;

public class CarShowUI extends javax.swing.JFrame {
  
  private OwnerManager ownerManager = null;
  private VehicleManager vehicleManager = null;
  private CarShowManager carShowManager = null;
  private CarShowOwnerManager carShowOwnerManager = null;
  private CarShowMainMenu carShowMainMenu = null;
  
  private final Container container = getContentPane();
  
  /**
   * Creates new form CarShowUI
   */
  public CarShowUI() {
    
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension windowSize = new Dimension((screenSize.width / 2) - 400, 
        (screenSize.height / 2) - 100);
    setPreferredSize(windowSize);
    setLocation(((screenSize.width - windowSize.width) / 2), 
        ((screenSize.height - windowSize.height) / 2));
    
    initComponents();
    setTitle("Vehicle Collection");
  }
  
  /**
   * Creates new form CarShowUI
   */
  public CarShowUI(CarShowMainMenu carShowMainMenu) throws Exception {
    
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension windowSize = new Dimension((screenSize.width / 2) - 400, 
        (screenSize.height / 2) - 100);
    setPreferredSize(windowSize);
    setLocation(((screenSize.width - windowSize.width) / 2), 
        ((screenSize.height - windowSize.height) / 2));
    
    initComponents();
    setTitle("Vehicle Collection");
    
    this.carShowMainMenu = carShowMainMenu;
    ownerManager = carShowMainMenu.getOwnerManager();
    vehicleManager = carShowMainMenu.getVehicleManager();
    carShowManager = carShowMainMenu.getCarShowManager();
    carShowOwnerManager = carShowMainMenu.getCarShowOwnerManager();
    
    Iterator<CarShow> itr = carShowManager.getCarShows();
    ArrayList<CarShow> carShowArrayList = new ArrayList<>();
    while (itr.hasNext()) {
      carShowArrayList.add((CarShow) itr.next());
    }
    
    carShowIdComboBox.removeAllItems();
    for (CarShow carShow : carShowArrayList) {
      carShowIdComboBox.addItem(carShow.getCarShowId());
    }
    carShowIdComboBox.setSelectedIndex(0);
    carShowIdComboBox.setEditable(true);
    
    carShowDatePicker.setDateToToday();
    
    CarShowUIController carShowUIController = new CarShowUIController(this);
    
    addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent ev){
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuItem1 = new javax.swing.JMenuItem();
    carShowIdLabel = new javax.swing.JLabel();
    carShowTitleLabel = new javax.swing.JLabel();
    carShowDateLabel = new javax.swing.JLabel();
    isSanctionedLabel = new javax.swing.JLabel();
    carShowInformationHeader = new javax.swing.JLabel();
    carShowTitleTextField = new javax.swing.JTextField();
    carShowDatePicker = new com.github.lgooddatepicker.components.DatePicker();
    isSanctionedCheckBox = new javax.swing.JCheckBox();
    findCarShowButton = new javax.swing.JButton();
    addCarShowButton = new javax.swing.JButton();
    removeCarShowButton = new javax.swing.JButton();
    carShowIdComboBox = new javax.swing.JComboBox<>();
    carShowMenuBar = new javax.swing.JMenuBar();
    fileCarShowMenuItem = new javax.swing.JMenu();
    exitCarShowMenuItem = new javax.swing.JMenuItem();
    editCarShowMenuItem = new javax.swing.JMenu();

    jMenuItem1.setText("jMenuItem1");

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    carShowIdLabel.setText("Car Show ID");
    carShowIdLabel.setToolTipText("");

    carShowTitleLabel.setText("Car Show Title");
    carShowTitleLabel.setToolTipText("");

    carShowDateLabel.setText("Car Show Date");
    carShowDateLabel.setToolTipText("");

    isSanctionedLabel.setText("Sanctioned");
    isSanctionedLabel.setToolTipText("Is Car Show sanctioned?");

    carShowInformationHeader.setText("Car Show Information");
    carShowInformationHeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

    carShowTitleTextField.setNextFocusableComponent(carShowDatePicker);

    carShowDatePicker.setNextFocusableComponent(isSanctionedCheckBox);

    isSanctionedCheckBox.setText("Yes");
    isSanctionedCheckBox.setNextFocusableComponent(findCarShowButton);
    isSanctionedCheckBox.setToolTipText("Check box if car show is sanctioned");

    findCarShowButton.setText("FIND");
    findCarShowButton.setNextFocusableComponent(addCarShowButton);
    findCarShowButton.setToolTipText("Find selected car show ");

    addCarShowButton.setText("ADD");
    addCarShowButton.setNextFocusableComponent(removeCarShowButton);
    addCarShowButton.setToolTipText("Add selected car show ");

    removeCarShowButton.setText("REMOVE");
    removeCarShowButton.setNextFocusableComponent(fileCarShowMenuItem);
    removeCarShowButton.setToolTipText("Remove selected car show ");

    carShowIdComboBox.setEditable(true);
    carShowIdComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    carShowIdComboBox.setFocusCycleRoot(true);
    carShowIdComboBox.setNextFocusableComponent(carShowTitleTextField);

    fileCarShowMenuItem.setText("File");
    fileCarShowMenuItem.setNextFocusableComponent(editCarShowMenuItem);

    exitCarShowMenuItem.setText("Exit");
    exitCarShowMenuItem.setToolTipText("Exit the system");
    fileCarShowMenuItem.add(exitCarShowMenuItem);

    carShowMenuBar.add(fileCarShowMenuItem);

    editCarShowMenuItem.setText("Edit");
    editCarShowMenuItem.setNextFocusableComponent(carShowIdComboBox);
    carShowMenuBar.add(editCarShowMenuItem);

    setJMenuBar(carShowMenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(carShowInformationHeader)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(carShowIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carShowTitleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isSanctionedLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carShowDateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
              .addComponent(findCarShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(addCarShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeCarShowButton))
              .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(carShowDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(isSanctionedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(carShowTitleTextField)
                  .addComponent(carShowIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        .addContainerGap(38, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addComponent(carShowInformationHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(carShowIdLabel)
          .addComponent(carShowIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(carShowTitleLabel)
          .addComponent(carShowTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(carShowDateLabel)
          .addComponent(carShowDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(16, 16, 16)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(isSanctionedLabel)
          .addComponent(isSanctionedCheckBox))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(findCarShowButton)
          .addComponent(addCarShowButton)
          .addComponent(removeCarShowButton))
        .addContainerGap(36, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CarShowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CarShowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CarShowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CarShowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new CarShowUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addCarShowButton;
  private javax.swing.JLabel carShowDateLabel;
  private com.github.lgooddatepicker.components.DatePicker carShowDatePicker;
  private javax.swing.JComboBox<String> carShowIdComboBox;
  private javax.swing.JLabel carShowIdLabel;
  private javax.swing.JLabel carShowInformationHeader;
  private javax.swing.JMenuBar carShowMenuBar;
  private javax.swing.JLabel carShowTitleLabel;
  private javax.swing.JTextField carShowTitleTextField;
  private javax.swing.JMenu editCarShowMenuItem;
  private javax.swing.JMenuItem exitCarShowMenuItem;
  private javax.swing.JMenu fileCarShowMenuItem;
  private javax.swing.JButton findCarShowButton;
  private javax.swing.JCheckBox isSanctionedCheckBox;
  private javax.swing.JLabel isSanctionedLabel;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JButton removeCarShowButton;
  // End of variables declaration//GEN-END:variables

  /**
   * 
   * @param carShow 
   * Fills fields with selected object
   */
  public void putCarShowInfo(CarShow carShow) {
    carShowIdComboBox.setSelectedItem(carShow.getCarShowId());
    carShowTitleTextField.setText(carShow.getCarShowTitle());
    carShowDatePicker.setDate(carShow.getCarShowDate());
    isSanctionedCheckBox.setSelected(carShow.getIsSanctioned());
  }
  
  /**
   * 
   * @return 
   * Returns object from field inputs
   */
  public CarShow getCarShowInfo() {
    CarShow carShow = new CarShow();
    
    carShow.setCarShowId((String) carShowIdComboBox.getSelectedItem());
    carShow.setCarShowTitle(carShowTitleTextField.getText());
    carShow.setCarShowDate(carShowDatePicker.getDate());
    carShow.setIsSanctioned(isSanctionedCheckBox.isSelected());
    
    return carShow;
  }
  
  /**
   * Empties input fields
   */
  public void clearCarShowInfo() {
    carShowIdComboBox.setSelectedIndex(0);
    carShowTitleTextField.setText("");
    carShowDatePicker.setDateToToday();
    isSanctionedCheckBox.setSelected(false);
  }
  
  public OwnerManager getOwnerManager() {
    return ownerManager;
  }

  public VehicleManager getVehicleManager() {
    return vehicleManager;
  }

  public CarShowManager getCarShowManager() {
    return carShowManager;
  }

  public CarShowOwnerManager getCarShowOwnerManager() {
    return carShowOwnerManager;
  }

  public CarShowMainMenu getCarShowMainMenu() {
    return carShowMainMenu;
  }

  public Container getContainer() {
    return container;
  }

  public javax.swing.JButton getAddCarShowButton() {
    return addCarShowButton;
  }

  public javax.swing.JLabel getCarShowDateLabel() {
    return carShowDateLabel;
  }

  public com.github.lgooddatepicker.components.DatePicker getCarShowDatePicker() {
    return carShowDatePicker;
  }

  public javax.swing.JComboBox<String> getCarShowIdComboBox() {
    return carShowIdComboBox;
  }

  public javax.swing.JLabel getCarShowIdLabel() {
    return carShowIdLabel;
  }

  public javax.swing.JLabel getCarShowInformationHeader() {
    return carShowInformationHeader;
  }

  public javax.swing.JMenuBar getCarShowMenuBar() {
    return carShowMenuBar;
  }

  public javax.swing.JLabel getCarShowTitleLabel() {
    return carShowTitleLabel;
  }

  public javax.swing.JTextField getCarShowTitleTextField() {
    return carShowTitleTextField;
  }

  public javax.swing.JMenu getEditCarShowMenuItem() {
    return editCarShowMenuItem;
  }

  public javax.swing.JMenuItem getExitCarShowMenuItem() {
    return exitCarShowMenuItem;
  }

  public javax.swing.JMenu getFileCarShowMenuItem() {
    return fileCarShowMenuItem;
  }

  public javax.swing.JButton getFindCarShowButton() {
    return findCarShowButton;
  }

  public javax.swing.JCheckBox getIsSanctionedCheckBox() {
    return isSanctionedCheckBox;
  }

  public javax.swing.JLabel getIsSanctionedLabel() {
    return isSanctionedLabel;
  }

  public javax.swing.JMenuItem getjMenuItem1() {
    return jMenuItem1;
  }

  public javax.swing.JButton getRemoveCarShowButton() {
    return removeCarShowButton;
  }
}
