/**
 *
 * @author David Beltran
 * File: OwnerUI.java
 * This file contains the OwnerUI class which is responsible for
 * displaying and running the car show application's Owner GUI
 */
package edu.du.beltrandavid.view;

import edu.du.beltrandavid.controllor.ownercontroller.OwnerUIController;
import edu.du.beltrandavid.model.business.manager.carshowmanager.CarShowManager;
import edu.du.beltrandavid.model.business.manager.carshowownermanager.CarShowOwnerManager;
import edu.du.beltrandavid.model.business.manager.ownermanager.OwnerManager;
import edu.du.beltrandavid.model.business.manager.vehiclemanager.VehicleManager;
import edu.du.beltrandavid.model.domain.Address;
import edu.du.beltrandavid.model.domain.Owner;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Iterator;

public class OwnerUI extends javax.swing.JFrame {
  
  private OwnerManager ownerManager = null;
  private VehicleManager vehicleManager = null;
  private CarShowManager carShowManager = null;
  private CarShowOwnerManager carShowOwnerManager = null;
  private CarShowMainMenu carShowMainMenu = null;
  
  private final Container container = getContentPane();
  
  /**
   * Creates new form OwnerUI
   */
  public OwnerUI() {
    
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension windowSize = new Dimension((screenSize.width / 2) - 100, 
        (screenSize.height / 2));
    setPreferredSize(windowSize);
    setLocation(((screenSize.width - windowSize.width) / 2), 
        ((screenSize.height - windowSize.height) / 2));
    
    initComponents();
    setTitle("Owner Collection");
  }
  
  /**
   * Creates new form OwnerUI
   * @param carShowMainMenu
   * @throws java.lang.Exception
   */
  public OwnerUI(CarShowMainMenu carShowMainMenu) throws Exception {
    
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension windowSize = new Dimension((screenSize.width / 2) - 100, 
        (screenSize.height / 2));
    setPreferredSize(windowSize);
    setLocation(((screenSize.width - windowSize.width) / 2), 
        ((screenSize.height - windowSize.height) / 2));
    
    initComponents();
    setTitle("Owner Collection");
    
    this.carShowMainMenu = carShowMainMenu;
    ownerManager = carShowMainMenu.getOwnerManager();
    vehicleManager = carShowMainMenu.getVehicleManager();
    carShowManager = carShowMainMenu.getCarShowManager();
    carShowOwnerManager = carShowMainMenu.getCarShowOwnerManager();
    
    Iterator<Owner> itr = ownerManager.getOwners();
    ArrayList<Owner> ownerArrayList = new ArrayList<>();
    while (itr.hasNext()) {
      ownerArrayList.add((Owner) itr.next());
    }
    
    ownerIdComboBox.removeAllItems();
    for (Owner owner: ownerArrayList) {
      ownerIdComboBox.addItem(owner.getOwnerId());
    }
    ownerIdComboBox.setSelectedIndex(0);
    ownerIdComboBox.setEditable(true);
    
    stateComboBox.removeAllItems();
    populateStateComboBox();
    stateComboBox.setSelectedItem("NV");
    
    OwnerUIController ownerUIController = new OwnerUIController(this);
    
    addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent ev){
      }
    });
    carShowMainMenu.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ownerIdLabel = new javax.swing.JLabel();
    firstNameLabel = new javax.swing.JLabel();
    firstNameTextField = new javax.swing.JTextField();
    lastNameLabel = new javax.swing.JLabel();
    lastNameTextField = new javax.swing.JTextField();
    ownerInformationHeader = new javax.swing.JLabel();
    phoneNumberLabel = new javax.swing.JLabel();
    phoneNumberTextField = new javax.swing.JTextField();
    numYearsLabel = new javax.swing.JLabel();
    numYearsTextField = new javax.swing.JTextField();
    addressInformationHeader = new javax.swing.JLabel();
    street1Label = new javax.swing.JLabel();
    street1TextField = new javax.swing.JTextField();
    street2Label = new javax.swing.JLabel();
    street2TextField = new javax.swing.JTextField();
    cityLabel = new javax.swing.JLabel();
    cityTextField = new javax.swing.JTextField();
    stateLabel = new javax.swing.JLabel();
    zipCodeLabel = new javax.swing.JLabel();
    zipCodeTextField = new javax.swing.JTextField();
    findOwnerButton = new javax.swing.JButton();
    addOwnerButton = new javax.swing.JButton();
    removeOwnerButton = new javax.swing.JButton();
    ownerIdComboBox = new javax.swing.JComboBox<>();
    stateComboBox = new javax.swing.JComboBox<>();
    ownerMainMenuBar = new javax.swing.JMenuBar();
    fileOwnerMenuItem = new javax.swing.JMenu();
    exitOwnerMenuItem = new javax.swing.JMenuItem();
    editOwnerMenuItem = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    ownerIdLabel.setText("Owner ID");
    ownerIdLabel.setToolTipText("");

    firstNameLabel.setText("First Name");

    firstNameTextField.setToolTipText("");
    firstNameTextField.setNextFocusableComponent(lastNameTextField);

    lastNameLabel.setText("Last Name");
    lastNameLabel.setToolTipText("");

    lastNameTextField.setNextFocusableComponent(phoneNumberTextField);

    ownerInformationHeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    ownerInformationHeader.setText("Owner Information");
    ownerInformationHeader.setName(""); // NOI18N

    phoneNumberLabel.setText("Phone Number");
    phoneNumberLabel.setToolTipText("");

    phoneNumberTextField.setToolTipText("");
    phoneNumberTextField.setNextFocusableComponent(numYearsTextField);

    numYearsLabel.setText("Number of Showing Years");
    numYearsLabel.setToolTipText("");

    numYearsTextField.setToolTipText("");
    numYearsTextField.setNextFocusableComponent(street1TextField);

    addressInformationHeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    addressInformationHeader.setText("Address Information");
    addressInformationHeader.setToolTipText("");

    street1Label.setText("Address Line 1");
    street1Label.setToolTipText("");

    street1TextField.setNextFocusableComponent(street2TextField);

    street2Label.setText("Address Line 2");
    street2Label.setToolTipText("");

    street2TextField.setNextFocusableComponent(cityTextField);

    cityLabel.setText("City");
    cityLabel.setToolTipText("");

    cityTextField.setNextFocusableComponent(stateComboBox);

    stateLabel.setText("State");
    stateLabel.setToolTipText("");

    zipCodeLabel.setText("Zip Code");
    zipCodeLabel.setToolTipText("");

    zipCodeTextField.setNextFocusableComponent(findOwnerButton);

    findOwnerButton.setText("FIND");
    findOwnerButton.setToolTipText("Find Selected Owner");
    findOwnerButton.setNextFocusableComponent(addOwnerButton);

    addOwnerButton.setText("ADD");
    addOwnerButton.setToolTipText("Add Selected Owner");
    addOwnerButton.setNextFocusableComponent(removeOwnerButton);

    removeOwnerButton.setText("REMOVE");
    removeOwnerButton.setToolTipText("Remove Selected Owner");
    removeOwnerButton.setNextFocusableComponent(fileOwnerMenuItem);

    ownerIdComboBox.setEditable(true);
    ownerIdComboBox.setFocusCycleRoot(true);
    ownerIdComboBox.setNextFocusableComponent(firstNameTextField);

    stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    fileOwnerMenuItem.setText("File");
    fileOwnerMenuItem.setNextFocusableComponent(editOwnerMenuItem);

    exitOwnerMenuItem.setText("Exit");
    exitOwnerMenuItem.setToolTipText("Exit the System");
    fileOwnerMenuItem.add(exitOwnerMenuItem);

    ownerMainMenuBar.add(fileOwnerMenuItem);

    editOwnerMenuItem.setText("Edit");
    editOwnerMenuItem.setNextFocusableComponent(ownerIdComboBox);
    ownerMainMenuBar.add(editOwnerMenuItem);

    setJMenuBar(ownerMainMenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(phoneNumberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(lastNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(ownerIdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(numYearsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(numYearsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(ownerIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(street1Label)
                      .addComponent(street2Label)
                      .addComponent(cityLabel)
                      .addComponent(stateLabel)
                      .addComponent(zipCodeLabel))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(street1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                      .addComponent(street2TextField)
                      .addComponent(cityTextField)
                      .addComponent(zipCodeTextField)
                      .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addComponent(addressInformationHeader)))
              .addGroup(layout.createSequentialGroup()
                .addComponent(findOwnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addComponent(addOwnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeOwnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(36, 36, 36))
          .addGroup(layout.createSequentialGroup()
            .addComponent(ownerInformationHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(ownerInformationHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(addressInformationHeader))
        .addGap(1, 1, 1)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(ownerIdLabel)
          .addComponent(street1Label)
          .addComponent(street1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ownerIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(firstNameLabel)
          .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(street2Label)
          .addComponent(street2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lastNameLabel)
          .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cityLabel)
          .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(phoneNumberLabel)
          .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(stateLabel)
          .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(numYearsLabel)
          .addComponent(numYearsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(zipCodeLabel)
          .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(50, 50, 50)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(findOwnerButton)
          .addComponent(addOwnerButton)
          .addComponent(removeOwnerButton))
        .addContainerGap(36, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(OwnerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(OwnerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(OwnerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(OwnerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new OwnerUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addOwnerButton;
  private javax.swing.JLabel addressInformationHeader;
  private javax.swing.JLabel cityLabel;
  private javax.swing.JTextField cityTextField;
  private javax.swing.JMenu editOwnerMenuItem;
  private javax.swing.JMenuItem exitOwnerMenuItem;
  private javax.swing.JMenu fileOwnerMenuItem;
  private javax.swing.JButton findOwnerButton;
  private javax.swing.JLabel firstNameLabel;
  private javax.swing.JTextField firstNameTextField;
  private javax.swing.JLabel lastNameLabel;
  private javax.swing.JTextField lastNameTextField;
  private javax.swing.JLabel numYearsLabel;
  private javax.swing.JTextField numYearsTextField;
  private javax.swing.JComboBox<String> ownerIdComboBox;
  private javax.swing.JLabel ownerIdLabel;
  private javax.swing.JLabel ownerInformationHeader;
  private javax.swing.JMenuBar ownerMainMenuBar;
  private javax.swing.JLabel phoneNumberLabel;
  private javax.swing.JTextField phoneNumberTextField;
  private javax.swing.JButton removeOwnerButton;
  private javax.swing.JComboBox<String> stateComboBox;
  private javax.swing.JLabel stateLabel;
  private javax.swing.JLabel street1Label;
  private javax.swing.JTextField street1TextField;
  private javax.swing.JLabel street2Label;
  private javax.swing.JTextField street2TextField;
  private javax.swing.JLabel zipCodeLabel;
  private javax.swing.JTextField zipCodeTextField;
  // End of variables declaration//GEN-END:variables

  /**
   *
   * @param owner
   * Fills all fields with object attributes when find button is triggered
   */
  public void putOwnerInfo(Owner owner) {
    Address address = owner.getAddress();
    
    ownerIdComboBox.setSelectedItem(owner.getOwnerId());
    firstNameTextField.setText(owner.getFirstName());
    lastNameTextField.setText(owner.getLastName());
    phoneNumberTextField.setText(owner.getPhoneNumber());
    numYearsTextField.setText(Integer.toString(owner.getNumYears()));
    street1TextField.setText(address.getStreet1());
    street2TextField.setText(address.getStreet2());
    cityTextField.setText(address.getCity());
    stateComboBox.setSelectedItem(address.getState());
    zipCodeTextField.setText(address.getZipCode());
  }
  
  /**
   *
   * @return
   * Instantiates object and stores in collection when add button is triggered
   */
  public Owner getOwnerInfo() {
    Owner owner = new Owner();
    Address address = new Address();
    
    owner.setOwnerId((String) ownerIdComboBox.getSelectedItem());
    owner.setFirstName(firstNameTextField.getText());
    owner.setLastName(lastNameTextField.getText());
    owner.setPhoneNumber(phoneNumberTextField.getText());
    owner.setNumYears(Integer.parseInt(numYearsTextField.getText()));
    
    address.setStreet1(street1TextField.getText());
    address.setStreet2(street2TextField.getText());
    address.setCity(cityTextField.getText());
    address.setState((String) stateComboBox.getSelectedItem());
    address.setZipCode(zipCodeTextField.getText());
    
    owner.setAddress(address);
    
    return owner;
  }
  
  /**
   * Empties all fields when remove button is triggered 
   */
  public void clearOwnerInfo() {
    ownerIdComboBox.setSelectedIndex(0);
    firstNameTextField.setText("");
    lastNameTextField.setText("");
    phoneNumberTextField.setText("");
    numYearsTextField.setText("");
    street1TextField.setText("");
    street2TextField.setText("");
    cityTextField.setText("");
    stateComboBox.setSelectedItem("NV");
    zipCodeTextField.setText("");
  }
  
  /**
   *
   * @return
   */
  public OwnerManager getOwnerManager() {
    return ownerManager;
  }

  /**
   *
   * @return
   */
  public VehicleManager getVehicleManager() {
    return vehicleManager;
  }

  /**
   *
   * @return
   */
  public CarShowManager getCarShowManager() {
    return carShowManager;
  }

  /**
   *
   * @return
   */
  public CarShowOwnerManager getCarShowOwnerManager() {
    return carShowOwnerManager;
  }

  /**
   *
   * @return
   */
  public CarShowMainMenu getCarShowMainMenu() {
    return carShowMainMenu;
  }

  /**
   *
   * @return
   */
  public Container getContainer() {
    return container;
  }

  /**
   *
   * @return
   */
  public javax.swing.JButton getAddOwnerButton() {
    return addOwnerButton;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getAddressInformationHeader() {
    return addressInformationHeader;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getCityLabel() {
    return cityLabel;
  }

  /**
   *
   * @return
   */
  public javax.swing.JTextField getCityTextField() {
    return cityTextField;
  }

  /**
   *
   * @return
   */
  public javax.swing.JMenu getEditOwnerMenuItem() {
    return editOwnerMenuItem;
  }

  /**
   *
   * @return
   */
  public javax.swing.JMenuItem getExitOwnerMenuItem() {
    return exitOwnerMenuItem;
  }

  /**
   *
   * @return
   */
  public javax.swing.JMenu getFileOwnerMenuItem() {
    return fileOwnerMenuItem;
  }

  /**
   *
   * @return
   */
  public javax.swing.JButton getFindOwnerButton() {
    return findOwnerButton;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getFirstNameLabel() {
    return firstNameLabel;
  }

  /**
   *
   * @return
   */
  public javax.swing.JTextField getFirstNameTextField() {
    return firstNameTextField;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getLastNameLabel() {
    return lastNameLabel;
  }

  /**
   *
   * @return
   */
  public javax.swing.JTextField getLastNameTextField() {
    return lastNameTextField;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getNumYearsLabel() {
    return numYearsLabel;
  }

  /**
   *
   * @return
   */
  public javax.swing.JTextField getNumYearsTextField() {
    return numYearsTextField;
  }

  /**
   *
   * @return
   */
  public javax.swing.JComboBox<String> getOwnerIdComboBox() {
    return ownerIdComboBox;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getOwnerIdLabel() {
    return ownerIdLabel;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getOwnerInformationHeader() {
    return ownerInformationHeader;
  }

  /**
   *
   * @return
   */
  public javax.swing.JMenuBar getOwnerMainMenuBar() {
    return ownerMainMenuBar;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getPhoneNumberLabel() {
    return phoneNumberLabel;
  }

  /**
   *
   * @return
   */
  public javax.swing.JTextField getPhoneNumberTextField() {
    return phoneNumberTextField;
  }

  /**
   *
   * @return
   */
  public javax.swing.JButton getRemoveOwnerButton() {
    return removeOwnerButton;
  }

  /**
   *
   * @return
   */
  public javax.swing.JComboBox<String> getStateComboBox() {
    return stateComboBox;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getStateLabel() {
    return stateLabel;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getStreet1Label() {
    return street1Label;
  }

  /**
   *
   * @return
   */
  public javax.swing.JTextField getStreet1TextField() {
    return street1TextField;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getStreet2Label() {
    return street2Label;
  }

  /**
   *
   * @return
   */
  public javax.swing.JTextField getStreet2TextField() {
    return street2TextField;
  }

  /**
   *
   * @return
   */
  public javax.swing.JLabel getZipCodeLabel() {
    return zipCodeLabel;
  }

  /**
   *
   * @return
   */
  public javax.swing.JTextField getZipCodeTextField() {
    return zipCodeTextField;
  }
  
  /**
   * Fills StateComboBox with non-editable options 
   */
  private void populateStateComboBox() {
    stateComboBox.addItem("AK");
    stateComboBox.addItem("AL");
    stateComboBox.addItem("AR");
    stateComboBox.addItem("AZ");
    stateComboBox.addItem("CA");
    stateComboBox.addItem("CO");
    stateComboBox.addItem("CT");
    stateComboBox.addItem("CZ");
    stateComboBox.addItem("DC");
    stateComboBox.addItem("DE");
    stateComboBox.addItem("FL");
    stateComboBox.addItem("GA");
    stateComboBox.addItem("GU");
    stateComboBox.addItem("HI");
    stateComboBox.addItem("IA");
    stateComboBox.addItem("ID");
    stateComboBox.addItem("IL");
    stateComboBox.addItem("IN");
    stateComboBox.addItem("KS");
    stateComboBox.addItem("KY");
    stateComboBox.addItem("LA");
    stateComboBox.addItem("MA");
    stateComboBox.addItem("MD");
    stateComboBox.addItem("ME");
    stateComboBox.addItem("MI");
    stateComboBox.addItem("MO");
    stateComboBox.addItem("MS");
    stateComboBox.addItem("MT");
    stateComboBox.addItem("NC");
    stateComboBox.addItem("ND");
    stateComboBox.addItem("NE");
    stateComboBox.addItem("NH");
    stateComboBox.addItem("NJ");
    stateComboBox.addItem("NM");
    stateComboBox.addItem("NV");
    stateComboBox.addItem("NY");
    stateComboBox.addItem("OH");
    stateComboBox.addItem("OK");
    stateComboBox.addItem("OR");
    stateComboBox.addItem("PA");
    stateComboBox.addItem("PR");
    stateComboBox.addItem("RI");
    stateComboBox.addItem("SC");
    stateComboBox.addItem("SD");
    stateComboBox.addItem("TN");
    stateComboBox.addItem("TX");
    stateComboBox.addItem("UT");
    stateComboBox.addItem("VA");
    stateComboBox.addItem("VI");
    stateComboBox.addItem("VT");
    stateComboBox.addItem("WA");
    stateComboBox.addItem("WI");
    stateComboBox.addItem("WV");
    stateComboBox.addItem("WY");
  }
}
